So, I'm just now gonna change the contents of `main.yml` to these:
  ```
name: Test Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test workflow"
  ```
  then push to github and see if the dot appears or what are my steps here exactly?